version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    command: "npm run dev"